version: "3.9"

services:
  mongo:
    image: mongo:7.0
    container_name: user_crud_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: user_crud_api
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app # mount source code for live reload
      - /app/node_modules # preserve node_modules inside container
    command: npm run dev

volumes:
  mongo-data:
